### ISSUE TITLE
TypeError: Cannot read properties of null

### ISSUE THREAD

**Issue by Sulpher** [exstreme/Jcomments-4#101]
смотрю сайт в lighthouse, вот что получаю:

TypeError: Cannot read properties of null (reading 'clientHeight') at JCommentsEditor.init (https://сайт.ru/media/com_jcomments/js/jcomments-v2.3.js:116:32) at new JCommentsEditor (https://сайт.ru/media/com_jcomments/js/jcomments-v2.3.js:16:7) at JCommentsInitializeForm (https://сайт.ru/:37:17)

<img width="474" alt="Снимок экрана 2022-07-22 в 10 01 58" src="https://user-images.githubusercontent.com/3432048/180382839-d0b617d7-b2ca-4b8a-a14f-3ef8cca59c55.png">

Дано: Joomla 4.1.5, JComments 4.0.22, Yootheme Pro - комменты выводятся через событие (после отображения содержимого).

**Comment by Globulopolis** [comment]
Комментирование работает? Если да, то предлагаю не обращать внимания.
